platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

target 'Yester' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTLinkingIOS',
    'RCTPushNotification',
    'RCTImage',
    'RCTActionSheet',
    'RCTImage',
    'RCTBlob',
    'RCTSettings',
    'RCTVibration',
    'RCTGeolocation',
    # Add any other subspecs you want to use in your project
  ]
  
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-onesignal',
  :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
  :inhibit_warnings => true

  #pod 'FBSDKCoreKit', '~>4.40.0'
  #pod 'FBSDKLoginKit', '~>4.40.0'
  #pod 'FBSDKShareKit', '~>4.40.0'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNPurchases', :path => '../node_modules/react-native-purchases',
  :inhibit_warnings => true

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNAWSCognito', :path => '../node_modules/amazon-cognito-identity-js'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'
  # Pods for Yester

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'YesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Yester-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Yester-tvOS

  target 'Yester-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
