platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'react-native-onesignal',
  :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
  :inhibit_warnings => true

end

target 'Yester' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTLinkingIOS',
    'RCTPushNotification',
    'RCTImage',
    'RCTActionSheet',
    'RCTImage',
    'RCTBlob',
    'RCTSettings',
    'RCTVibration',
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'FBSDKCoreKit', '~>4.40.0'
  # pod 'FBSDKLoginKit', '~>4.40.0'
  # pod 'FBSDKShareKit', '~>4.40.0'

  # pod 'react-native-onesignal',
  #   :path => "../node_modules/react-native-onesignal/react-native-onesignal.podspec",
  #   :inhibit_warnings => true

  # Pods for Yester

  target 'YesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Yester-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Yester-tvOS

  target 'Yester-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
